title: terrain-maker
description: 3D terrain visualization with Blender from DEM data
remote_theme: just-the-docs/just-the-docs@v0.10.0
baseurl: /terrain-maker_v2
url: https://jflournoy.github.io

# Color scheme
color_scheme: light

# Enable search
search_enabled: true
search:
  heading_level: 3
  previews: 3

# Aux links (top right)
aux_links:
  "GitHub":
    - "https://github.com/jflournoy/terrain-maker_v2"

# Footer
footer_content: "terrain-maker &copy; 2026"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Heading anchor links
heading_anchors: true
