title: terrain-maker
description: 3D terrain visualization with Blender from DEM data
remote_theme: pages-themes/cayman@v0.2.0

baseurl: /terrain-maker_v2
url: https://jflournoy.github.io

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 2..4
